package api

var apiErrors = map[int]string{
	1:   "EINTERNAL (-1): An internal error has occurred.",
	2:   "EARGS (-2): You have passed invalid arguments to this command.",
	3:   "EAGAIN (-3): Temporary congestion or server malfunction prevented request processing.",
	4:   "ERATELIMIT (-4): You have exceeded your command quota.",
	5:   "EFAILED (-5): The upload failed.",
	6:   "ETOOMANY (-6): Too many concurrent IP addresses are accessing this upload target URL.",
	7:   "ERANGE (-7): The upload packet is out of range.",
	8:   "EEXPIRED (-8): Upload target URL has expired.",
	9:   "ENOENT (-9): Object not found.",
	10:  "ECIRCULAR (-10): Circular linkage attempted.",
	11:  "EACCESS (-11): Access violation.",
	12:  "EEXIST (-12): Object already exists.",
	13:  "EINCOMPLETE (-13): Incomplete resource.",
	14:  "EKEY (-14): Decryption failed.",
	15:  "ESID (-15): Invalid or expired session.",
	16:  "EBLOCKED (-16): User blocked.",
	17:  "EOVERQUOTA (-17): Request over quota.",
	18:  "ETEMPUNAVAIL (-18): Resource temporarily unavailable.",
	19:  "ETOOMANYCONNECTIONS (-19)",
	24:  "EGOINGOVERQUOTA (-24)",
	25:  "EROLLEDBACK (-25)",
	26:  "EMFAREQUIRED (-26): Multi-Factor Authentication Required.",
	27:  "EMASTERONLY (-27)",
	28:  "EBUSINESSPASTDUE (-28)",
	29:  "EPAYWALL (-29): ODQ paywall state.",
	400: "ETOOERR (-400)",
	401: "ESHAREROVERQUOTA (-401)",
}
